my_plugin/config/routes.rb
MyPlugin::Application.routes.draw do
  devise_for :users

  get "home/index"

  resources :profiles

 root :to => "home#index"

end

my_plugin/app/models/profile.rb
class Profile < ActiveRecord::Base
end

my_plugin/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :lockable, :timeoutable and :activatable
  devise :database_authenticatable, :registerable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation
end
# migration
class DeviseCreateUsers < ActiveRecord::Migration
  def self.up
    create_table(:users) do |t|
      t.database_authenticatable :null => false
      # t.confirmable
      t.recoverable
      t.rememberable
      t.trackable
      # t.lockable :lock_strategy => :failed_attempts, :unlock_strategy => :both

      t.timestamps
    end

    add_index :users, :email,                :unique => true
    # add_index :users, :confirmation_token,   :unique => true
    add_index :users, :reset_password_token, :unique => true
    # add_index :users, :unlock_token,         :unique => true
  end

  def self.down
    drop_table :users
  end

end

# migration

my_plugin/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

 
  
end

my_plugin/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

my_plugin/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  # GET /profiles
  # GET /profiles.xml
 #before_filter :authenticate, :except => [:index, :show, :create]
prawnto :prawn => { :top_margin => 75 }

def show
  @profile = Profile.find(params[:id])
end
  def index


    @profiles = Profile.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @profiles }
    end
  end

  # GET /profiles/1
  # GET /profiles/1.xml
  def show
    @profile = Profile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # GET /profiles/new
  # GET /profiles/new.xml
  def new
    @profile = Profile.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @profile }
    end
  end

  # GET /profiles/1/edit
  def edit
    @profile = Profile.find(params[:id])
  end

  # POST /profiles
  # POST /profiles.xml
  def create
    @profile = Profile.new(params[:profile])

    respond_to do |format|
      if @profile.save
        format.html { redirect_to(@profile, :notice => 'Profile was successfully created.') }
        format.xml  { render :xml => @profile, :status => :created, :location => @profile }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /profiles/1
  # PUT /profiles/1.xml
  def update
    @profile = Profile.find(params[:id])

    respond_to do |format|
      if @profile.update_attributes(params[:profile])
        format.html { redirect_to(@profile, :notice => 'Profile was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @profile.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.xml
  def destroy
    @profile = Profile.find(params[:id])
    @profile.destroy

    respond_to do |format|
      format.html { redirect_to(profiles_url) }
      format.xml  { head :ok }
    end
  end
end

my_plugin/app/helpers/application_helper.rb
module ApplicationHelper
end

my_plugin/app/helpers/home_helper.rb
module HomeHelper
end

my_plugin/app/helpers/profiles_helper.rb
module ProfilesHelper
end

my_plugin/app/views/profiles/_form.html.erb
<%= form_for(@profile) do |f| %>
  <% if @profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% @profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.text_field :age %>
  </div>
  <div class="field">
    <%= f.label :qualification %><br />
    <%= f.text_field :qualification %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :designation %><br />
    <%= f.text_field :designation %>
  </div>
  <div class="field">
    <%= f.label :salary %><br />
    <%= f.text_field :salary %>
  </div>
  <div class="field">
    <%= f.label :about_yourself %><br />
    <%= f.text_area :about_yourself %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

my_plugin/app/views/profiles/edit.html.erb
<h1>Editing profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

my_plugin/app/views/profiles/index.html.erb
<h1>Listing profiles</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Qualification</th>
    <th>Address</th>
    <th>Designation</th>
    <th>Salary</th>
    <th>About yourself</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profiles.each do |profile| %>
  <tr>
    <td><%= profile.name %></td>
    <td><%= profile.age %></td>
    <td><%= profile.qualification %></td>
    <td><%= profile.address %></td>
    <td><%= profile.designation %></td>
    <td><%= profile.salary %></td>
    <td><%= profile.about_yourself %></td>
    <% if user_signed_in? %>
    <td><%= link_to 'Show', profile %></td>
    <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
    <td><%= link_to 'Destroy', profile, :confirm => 'Are you sure?', :method => :delete %></td>
     <% end %>
  </tr>
<% end %>
</table>

<br />
 <% if user_signed_in? %>
<%= link_to 'New Profile', new_profile_path %>
 <% end %>

my_plugin/app/views/profiles/new.html.erb
<h1>New profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

my_plugin/app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @profile.name %>
</p>

<p>
  <b>Age:</b>
  <%= @profile.age %>
</p>

<p>
  <b>Qualification:</b>
  <%= @profile.qualification %>
</p>

<p>
  <b>Address:</b>
  <%= @profile.address %>
</p>

<p>
  <b>Designation:</b>
  <%= @profile.designation %>
</p>

<p>
  <b>Salary:</b>
  <%= @profile.salary %>
</p>

<p>
  <b>About yourself:</b>
  <%= @profile.about_yourself %>
</p>


<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', profiles_path %>

<p><%= link_to "Printable Invoice (PDF)", profile_path(@profile, :format => 'pdf') %></p>