rubystuff/One_to_many_relation_app/config/routes.rb
One_to_many_relation_app::Application.routes.draw do
  resources :banks

  resources :banks do
  resources :credits
  end

  get "home/index"

root :to => "home#index"

end

rubystuff/One_to_many_relation_app/app/models/bank.rb
class Bank < ActiveRecord::Base
 has_one :credit
end

rubystuff/One_to_many_relation_app/app/models/credit.rb
class Credit < ActiveRecord::Base
  belongs_to :banks
end

rubystuff/One_to_many_relation_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

rubystuff/One_to_many_relation_app/app/controllers/banks_controller.rb
class BanksController < ApplicationController
  # GET /banks
  # GET /banks.xml
  def index
    @banks = Bank.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @banks }
    end
  end

  # GET /banks/1
  # GET /banks/1.xml
  def show
    @bank = Bank.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bank }
    end
  end

  # GET /banks/new
  # GET /banks/new.xml
  def new
    @bank = Bank.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bank }
    end
  end

  # GET /banks/1/edit
  def edit
    @bank = Bank.find(params[:id])
  end

  # POST /banks
  # POST /banks.xml
  def create
    @bank = Bank.new(params[:bank])

    respond_to do |format|
      if @bank.save
        format.html { redirect_to(@bank, :notice => 'Bank was successfully created.') }
        format.xml  { render :xml => @bank, :status => :created, :location => @bank }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bank.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /banks/1
  # PUT /banks/1.xml
  def update
    @bank = Bank.find(params[:id])

    respond_to do |format|
      if @bank.update_attributes(params[:bank])
        format.html { redirect_to(@bank, :notice => 'Bank was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bank.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /banks/1
  # DELETE /banks/1.xml
  def destroy
    @bank = Bank.find(params[:id])
    @bank.destroy

    respond_to do |format|
      format.html { redirect_to(banks_url) }
      format.xml  { head :ok }
    end
  end
end

rubystuff/One_to_many_relation_app/app/controllers/credits_controller.rb
class CreditsController < ApplicationController
def create
    @bank = Bank.find(params[:bank_id])
    @credit = @bank.credits.create(params[:credit_by])
    redirect_to bank_path(@bank)
  end
end

rubystuff/One_to_many_relation_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

rubystuff/One_to_many_relation_app/app/helpers/application_helper.rb
module ApplicationHelper
end

rubystuff/One_to_many_relation_app/app/helpers/banks_helper.rb
module BanksHelper
end

rubystuff/One_to_many_relation_app/app/helpers/credits_helper.rb
module CreditsHelper
end

rubystuff/One_to_many_relation_app/app/helpers/home_helper.rb
module HomeHelper
end

rubystuff/One_to_many_relation_app/app/views/banks/_form.html.erb
<%= form_for(@bank) do |f| %>
  <% if @bank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bank.errors.count, "error") %> prohibited this bank from being saved:</h2>

      <ul>
      <% @bank.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :account_number %><br />
    <%= f.text_field :account_number %>
  </div>
  <div class="field">
    <%= f.label :account_type %><br />
    <%= f.text_field :account_type %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rubystuff/One_to_many_relation_app/app/views/banks/edit.html.erb
<h1>Editing bank</h1>

<%= render 'form' %>

<%= link_to 'Show', @bank %> |
<%= link_to 'Back', banks_path %>

rubystuff/One_to_many_relation_app/app/views/banks/index.html.erb
<h1>Listing banks</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Account number</th>
    <th>Account type</th>
    <th>Address</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @banks.each do |bank| %>
  <tr>
    <td><%= bank.name %></td>
    <td><%= bank.account_number %></td>
    <td><%= bank.account_type %></td>
    <td><%= bank.address %></td>
    <td><%= link_to 'Show', bank %></td>
    <td><%= link_to 'Edit', edit_bank_path(bank) %></td>
    <td><%= link_to 'Destroy', bank, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bank', new_bank_path %>

rubystuff/One_to_many_relation_app/app/views/banks/new.html.erb
<h1>New bank</h1>

<%= render 'form' %>

<%= link_to 'Back', banks_path %>

rubystuff/One_to_many_relation_app/app/views/banks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @bank.name %>
</p>

<p>
  <b>Account number:</b>
  <%= @bank.account_number %>
</p>

<p>
  <b>Account type:</b>
  <%= @bank.account_type %>
</p>

<p>
  <b>Address:</b>
  <%= @bank.address %>
</p>


<%= render :partial => "credits/credit",
           :collection => @bank.credits %>

<h2>Add a credit:</h2>
<%= render "credits/form" %>
 
<%= link_to 'Edit', edit_bank_path(@bank) %> |
<%= link_to 'Back', banks_path %>